---
title: "Jesse Analysis"
output: html_notebook
author: Jesse Dykes
---

```{r}
library(knitr)
library(tidyverse)
library(janitor)
library(lubridate) # because we will probably see some dates
library(here) # more easily access files in your project
library(sf) # working with simple features - geospatial
library(tmap)
library(tidycensus)
```


```{r}
bikes = (read.csv(here("data_raw", "202309-capitalbikeshare-tripdata.csv")))
racks = st_read(here("data_raw", "Public_Bike_Racks.geojson")) |> clean_names()
```

```{r}
dfShops = st_read(here("data_raw","Shopping_Centers.geojson")) |> clean_names()
pub_schools = st_read(here("data_raw", "DC_Public_Schools.geojson")) |> clean_names()
```

```{r}
bike_s = bikes |> slice_sample(n = 100 )
shops = dfShops |> select(geometry,name)
```

```{r}
census_api_key("9fc5d3792d3a5e922287c3f4e9995118766d50a2")

```
```{r}
v2018 = load_variables(2018, "acs5")
```

```{r}

df_cencus=get_acs(geography = "tract",
                  variables=c("vehicles"="B08141_001",
                              "population" = "B01001_001",
                              "public_transportion" = "B08006_008"),
                  state="DC",geometry=TRUE,year=2021) 

df_cens=df_cencus %>% 
  select(-moe) %>% 
  pivot_wider(names_from = "variable", 
              values_from = "estimate")

df_cens = df_cens |>
  mutate("v_to_p" = vehicles / population, "pub_transport_to_p" = public_transportion / population)

df_cens_adj = df_cens |> st_transform(4326)
```

```{r}

tmap_mode("view")

tm_shape(df_cens) +tm_polygons(c("v_to_p", "pub_transport_to_p"), alpha=.5) + tm_shape(shops) + tm_dots(col = "#FF3300", size = 0.1, alpha = 0.5) + tm_shape(racks) + tm_dots(col = "#AEEDE2", size = 0.06, alpha = 0.5)
```

```{r}

```

