---
title: "How the flow of traffic of cars correlates with bike share data"
output: html_notebook
---

- Look for areas that people do not use cars as much in 
- Put more bikes in the areas where there are less people commuting to work in cars
- Relation between motorized vehicles and bikes
- Parking spaces
- Last mile
- Where best to place bike stations 



```{r}
library(knitr)
library(tidyverse)
library(janitor)
library(lubridate) # because we will probably see some dates
library(here) # more easily access files in your project
library(sf) # working with simple features - geospatial
library(tmap)
library(tidycensus)
```

```{r}
bikes = (read.csv(here("data_raw", "202309-capitalbikeshare-tripdata.csv"))) |> clean_names()
```

```{r}

racks = st_read((here("data_raw", "Public_Bike_Racks.geojson"))) |> clean_names() 
```


```{r}
bike_s = bikes |> slice_sample(n = 100 )
```

```{r}
census_api_key("9fc5d3792d3a5e922287c3f4e9995118766d50a2")

```
```{r}
v2018 = load_variables(2018, "acs5")
```

```{r}
df_censcus=get_acs(geography = "tract",
                  variables=c("vehicles"="B08141_001",
                              "population" = "B01001_001",
                              "public_transportion" = "B08006_008"),
                  state="DC",geometry=TRUE,year=2021) 
```
```{r}
plot(df_censcus)
plot(racks)

```
```{r}
```

```{r}

tmap_mode("view")

df_cens=df_censcus %>% 
  select(-moe) %>% 
  pivot_wider(names_from = "variable", 
              values_from = "estimate")|> 
  mutate(pub_pop = public_transportion / population,
         v_pop = vehicles / population)



```

```{r}
bike_routes = st_read((here("data_raw", "Signed_Bike_Routes.geojson"))) |> clean_names() 
```


```{r}
df_cens_adj = df_cens |> st_transform(4326)
bike_routes = st_as_sf(bike_routes, crs=st_crs(df_cens_adj))

racks = st_as_sf(racks, crs=st_crs(df_cens_adj))
tm_shape(df_cens) +tm_polygons(c("pub_pop", "v_pop"), alpha=.5) + tm_shape(racks) +tm_symbols(size = 0.01, alpha = 0.5) +   
tm_shape(bike_routes) + tm_lines(col="blue",lwd=1,alpha= 1)
```


# Data Sources:

Public Bike Racks: https://opendata.dc.gov/explore?collection=Dataset&query=Public%20Bike%20Racks
Bike Share Data: https://capitalbikeshare.com/system-data
Signed Bike Routes: https://opendata.dc.gov/explore?collection=Dataset&query=Bike%20Routes


